### PR TITLE
Desef style

### PR DESCRIPTION
**Pull request by projekter**
Added demo presentation that uses my style.
I have tried to create quite a generic approach. This style also contains lots of definitions. Features:
- Contains a navigation bar, using `Hannover` theme.
- Redefinition of the `\note` command: Notes are automatically typeset at the same y-position as their text. This is something very useful as soon as [#58](https://github.com/dannyedel/dspdfviewer/issues/58) is fixed.
- Notes can contain hyperlinks. Although PGF manual says it is not possible to maintain hyperlink functionality with `pgfpages`, I have found a way (for this special layout; any differing page layout [notes not on the right side] would need special treatment) to fix this.
- `peek`-Environment which allows to show the contents of the next slide instead of notes. For this, I have used the `pgfmorepages` package from [TeX-SX launchpad](http://bazaar.launchpad.net/~tex-sx/tex-sx/development/files) and portions of [this SO post](http://tex.stackexchange.com/a/60628). However, I have patched the `pgfmorepages` (which is based on an older version of PGF) so that hyperlinks aren't broken any more.
- Fixed a bug in beamer which will produce endless warnings as soon as notes are enabled because of duplicated hypertargets.
- Navigation bar entries can be indented properly if they contain enumeration-like characters and are more than one line long (in the example, `§1 This is a long text` would be adjusted that the second line starts behind `§1`).
- Section-end marker defined which adds a symbol to the bottom right of the notes page to indicate that a section is now over (insert manually, with customizable text).
- Adjustable line spacing in content and notes, which will not affect the navigation.
- Notes can be switched on or of via one simple definition.

### CODE REVIEW

**Comment by dannyedel** [comment]
Wow that is pretty cool!

Just two things and I'll import this:
- Please don't remove `.pdf` filetype from gitignore, this should be a pure source repository
- Please don't commit the compilation result

If you could remove the pdf and undo the .gitignore change (rewriting history/squashing/force-pushing) that would be awesome.

**Comment by projekter** [comment]
I mainly changed the .gitignore to add the synctex filetype (.synctex.gz) to it. Removing the PDF is okay, but synctex should stay excluded, shouldn't it?

**Comment by dannyedel** [comment]
Aye, block synctex in gitignore. Its just as much a compilation result as the PDF.

**Comment by projekter** [comment]
Done.

**Comment by dannyedel** [comment]
Please `squash` the commits and (force-)push again, so that the history doesnt contain [binary add] [binary remove].

**Comment by projekter** [comment]
I hate git. Incredible.
I have forked the project and created a fresh [pull request](https://github.com/dannyedel/example-beamer-presentations/pull/2) with a clean history, as rebasing did not work.

**Pull request closed without merging**
